### ISSUE TITLE
Structuring of the data

### ISSUE THREAD

**Issue by LaurensCorbiere** [PatRyg99/eigenvector-grouping#1]
I have a dataset of the manual (label) and automatic (by Unet) segmentation of human carotid vessels. I have converted the segmentations of the manual and automatic segmentations to 3D point clouds. How should I structure the data to be able to train the PointNet++ on these point clouds? That doesn't become clear to me from your repository of the Pointnet2 repository. Could you give an example how you structured your data as an input?

**Comment by PatRyg99** [comment]
Input point clouds should be of the format: $N \times 4$, where $N$ - number of points, and for each point there is a tuple $(x, y, z, L)$ where $(x, y, z)$ are 3D coordinates of a given point and $L$ is a GT label. If you have data in a different format you can just plug your own transforms since in the `training_step` in `SegmentatorModule` point cloud is already split into coordinates $(x, y, z)$ and labels $(L,)$.

**Comment by LaurensCorbiere** [comment]
Thanks for your clear explanation!

I assume that this is a format for the point clouds of one patient. How do I structure the point clouds of multiple patients?

**Comment by PatRyg99** [comment]
Yes, that's for one patient, I stored point clouds for each patient in separate files. I'm using `Monai` dataset, which expects data to be provided as a list of dictionaries, so with separate files for each patient, my input list to the dataset object looks like this:

```python
[
    {"input": "path/to/sample_1.npy"},
    {"input": "path/to/sample_2.npy"},
    ...
    {"input": "path/to/sample_n.npy"}
]
```

If you store all patients in one file you can just load it a priori, built a list of format provided above and skip `LoadImaged` transform.
